### PR TITLE
feat: Somewhat Useful Exceptions for Unsupported Objects

### PR DESCRIPTION
**Pull request by robodair**
I hit a few edges when testing pydantic-glue out, and I've added a few exceptions with a bit more detail about what's going on.

### CODE REVIEW

**Comment by svdimchenko** [comment]
> I hit a few edges when testing pydantic-glue out, and I've added a few exceptions with a bit more detail about what's going on.

Hi there @robodair ! Thanks for your contribution. The code looks OK to me. Pls fix the pre-commit check and we can merge it.

**Comment by robodair** [comment]
@svdimchenko I also have some changes to support specifying the `timestamp` glue type for fields that are an `int` with  `{"format": "unixtime"} specified in `json_schema_extra`, would you like those proposed here or in a separate PR?

It's a peculiarity about the "correct" way to store timestamps in the schema I'm using.

**Comment by robodair** [comment]
@svdimchenko should be ready to go now!

**Comment by robodair** [comment]
Hey @svdimchenko I'd love to see this merged so I can consume a more official release, would you be able to kick off the pipeline and merge?

**Comment by svdimchenko** [comment]
> Hey @svdimchenko I'd love to see this merged so I can consume a more official release, would you be able to kick off the pipeline and merge?

Hey @robodair the pre-commit check is still failed, pls fix.

**Comment by robodair** [comment]
@svdimchenko Serves me right, the node version on my work machine was too old so I skipped just the markdownlint check.

I enabled actions in my fork and have rectified the issues there.

I also noticed an issue in this repository when I did that, I got a failure on test 3.9 which didn't occur in the checks here. Turns out that the test actions on `main` in this repo all ran on Python 3.12: https://github.com/svdimchenko/pydantic-glue/actions/runs/11770931878/job/32982167948 which probably isn't want you want.

Looked into it, was a cache key issue, fixed by assigning an `id` to the `python-version` step, which I've added to this PR.

:crossed_fingers: finally good to merge now I think

**Review by svdimchenko — APPROVED** [review]
thanks a lot for you contribution @robodair ! I'll merge and release the new version 💯

**Pull request merged**
